"""Ajout du champ outputFilenameTemplate

Revision ID: 2d8d214d3548
Revises: 923fea36d124
Create Date: 2025-10-03 11:43:41.981228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8d214d3548'
down_revision: Union[str, Sequence[str], None] = '923fea36d124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('outputFilenameTemplate', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'outputFilenameTemplate')
    # ### end Alembic commands ###
